// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO hub.sessions (token, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO hub.users (display_name) VALUES ($1) RETURNING id
`

// Auth: пользователи, сессии, OAuth-связки (тикет 003)
func (q *Queries) CreateUser(ctx context.Context, displayName string) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM hub.identities WHERE id = $1 AND user_id = $2
`

type DeleteIdentityParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM hub.sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const findIdentityByProviderUser = `-- name: FindIdentityByProviderUser :one
SELECT id, user_id, provider, provider_user_id, username,
       access_token_enc, refresh_token_enc, token_expires_at, created_at
  FROM hub.identities
 WHERE provider = $1 AND provider_user_id = $2
`

type FindIdentityByProviderUserParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) FindIdentityByProviderUser(ctx context.Context, arg FindIdentityByProviderUserParams) (HubIdentity, error) {
	row := q.db.QueryRow(ctx, findIdentityByProviderUser, arg.Provider, arg.ProviderUserID)
	var i HubIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const identities = `-- name: Identities :many
SELECT id, user_id, provider, provider_user_id, username,
       access_token_enc, refresh_token_enc, token_expires_at, created_at
  FROM hub.identities WHERE user_id = $1 ORDER BY id
`

func (q *Queries) Identities(ctx context.Context, userID int64) ([]HubIdentity, error) {
	rows, err := q.db.Query(ctx, identities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubIdentity
	for rows.Next() {
		var i HubIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Username,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.TokenExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identity = `-- name: Identity :one
SELECT id, user_id, provider, provider_user_id, username,
       access_token_enc, refresh_token_enc, token_expires_at, created_at
  FROM hub.identities WHERE id = $1 AND user_id = $2
`

type IdentityParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) Identity(ctx context.Context, arg IdentityParams) (HubIdentity, error) {
	row := q.db.QueryRow(ctx, identity, arg.ID, arg.UserID)
	var i HubIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :one
INSERT INTO hub.identities
  (user_id, provider, provider_user_id, username, access_token_enc, refresh_token_enc, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertIdentityParams struct {
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  *time.Time
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Username,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const sessionUser = `-- name: SessionUser :one
SELECT user_id FROM hub.sessions WHERE token = $1 AND expires_at > now()
`

func (q *Queries) SessionUser(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, sessionUser, token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const updateIdentityTokens = `-- name: UpdateIdentityTokens :exec
UPDATE hub.identities
   SET username = $1, access_token_enc = $2,
       refresh_token_enc = COALESCE($3::bytea, refresh_token_enc),
       token_expires_at = $4
 WHERE id = $5
`

type UpdateIdentityTokensParams struct {
	Username        string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  *time.Time
	ID              int64
}

func (q *Queries) UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error {
	_, err := q.db.Exec(ctx, updateIdentityTokens,
		arg.Username,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
		arg.ID,
	)
	return err
}

const userDisplayName = `-- name: UserDisplayName :one
SELECT display_name FROM hub.users WHERE id = $1
`

func (q *Queries) UserDisplayName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, userDisplayName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}
