// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package db

import (
	"context"
)

const build = `-- name: Build :one
SELECT id, user_id, name, llm_connection_id, sandbox_connection_id,
       prompt, memory_preset, limits, created_at
  FROM hub.agent_builds WHERE id = $1
`

func (q *Queries) Build(ctx context.Context, id int64) (HubAgentBuild, error) {
	row := q.db.QueryRow(ctx, build, id)
	var i HubAgentBuild
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LlmConnectionID,
		&i.SandboxConnectionID,
		&i.Prompt,
		&i.MemoryPreset,
		&i.Limits,
		&i.CreatedAt,
	)
	return i, err
}

const builds = `-- name: Builds :many

SELECT id, user_id, name, llm_connection_id, sandbox_connection_id,
       prompt, memory_preset, limits, created_at
  FROM hub.agent_builds WHERE user_id = $1 ORDER BY id
`

// Сборки Агента и Подключения
func (q *Queries) Builds(ctx context.Context, userID int64) ([]HubAgentBuild, error) {
	rows, err := q.db.Query(ctx, builds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubAgentBuild
	for rows.Next() {
		var i HubAgentBuild
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LlmConnectionID,
			&i.SandboxConnectionID,
			&i.Prompt,
			&i.MemoryPreset,
			&i.Limits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO hub.agent_builds
  (user_id, name, llm_connection_id, sandbox_connection_id, prompt, memory_preset, limits)
VALUES ($1, $2, $3, $4, $5, $6,
        COALESCE($7::jsonb, '{}'::jsonb))
RETURNING id
`

type CreateBuildParams struct {
	UserID              int64
	Name                string
	LlmConnectionID     int64
	SandboxConnectionID int64
	Prompt              *string
	MemoryPreset        *string
	Limits              []byte
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (int64, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.UserID,
		arg.Name,
		arg.LlmConnectionID,
		arg.SandboxConnectionID,
		arg.Prompt,
		arg.MemoryPreset,
		arg.Limits,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLlmConnection = `-- name: CreateLlmConnection :one
INSERT INTO hub.llm_connections (user_id, name, api_base, api_key_enc, model)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateLlmConnectionParams struct {
	UserID    int64
	Name      string
	APIBase   string
	APIKeyEnc []byte
	Model     string
}

func (q *Queries) CreateLlmConnection(ctx context.Context, arg CreateLlmConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLlmConnection,
		arg.UserID,
		arg.Name,
		arg.APIBase,
		arg.APIKeyEnc,
		arg.Model,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSandboxConnection = `-- name: CreateSandboxConnection :one
INSERT INTO hub.sandbox_connections (name, domain, api_key_enc, image)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateSandboxConnectionParams struct {
	Name      string
	Domain    string
	APIKeyEnc []byte
	Image     *string
}

func (q *Queries) CreateSandboxConnection(ctx context.Context, arg CreateSandboxConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSandboxConnection,
		arg.Name,
		arg.Domain,
		arg.APIKeyEnc,
		arg.Image,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBuild = `-- name: DeleteBuild :execrows
DELETE FROM hub.agent_builds WHERE id = $1 AND user_id = $2
`

type DeleteBuildParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteBuild(ctx context.Context, arg DeleteBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBuild, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLlmConnection = `-- name: DeleteLlmConnection :execrows
DELETE FROM hub.llm_connections WHERE id = $1 AND user_id = $2
`

type DeleteLlmConnectionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteLlmConnection(ctx context.Context, arg DeleteLlmConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLlmConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSandboxConnection = `-- name: DeleteSandboxConnection :execrows
DELETE FROM hub.sandbox_connections WHERE id = $1
`

func (q *Queries) DeleteSandboxConnection(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSandboxConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const llmConnections = `-- name: LlmConnections :many
SELECT id, user_id, name, api_base, api_key_enc, model, created_at
  FROM hub.llm_connections WHERE user_id = $1 ORDER BY id
`

func (q *Queries) LlmConnections(ctx context.Context, userID int64) ([]HubLlmConnection, error) {
	rows, err := q.db.Query(ctx, llmConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubLlmConnection
	for rows.Next() {
		var i HubLlmConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.APIBase,
			&i.APIKeyEnc,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sandboxConnection = `-- name: SandboxConnection :one
SELECT id, name, domain, api_key_enc, image, created_at FROM hub.sandbox_connections WHERE id = $1
`

func (q *Queries) SandboxConnection(ctx context.Context, id int64) (HubSandboxConnection, error) {
	row := q.db.QueryRow(ctx, sandboxConnection, id)
	var i HubSandboxConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.APIKeyEnc,
		&i.Image,
		&i.CreatedAt,
	)
	return i, err
}

const sandboxConnections = `-- name: SandboxConnections :many
SELECT id, name, domain, api_key_enc, image, created_at FROM hub.sandbox_connections ORDER BY id
`

func (q *Queries) SandboxConnections(ctx context.Context) ([]HubSandboxConnection, error) {
	rows, err := q.db.Query(ctx, sandboxConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubSandboxConnection
	for rows.Next() {
		var i HubSandboxConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.APIKeyEnc,
			&i.Image,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuild = `-- name: UpdateBuild :execrows
UPDATE hub.agent_builds
   SET name = $1, llm_connection_id = $2, sandbox_connection_id = $3,
       prompt = $4, memory_preset = $5,
       limits = COALESCE($6::jsonb, '{}'::jsonb)
 WHERE id = $7 AND user_id = $8
`

type UpdateBuildParams struct {
	Name                string
	LlmConnectionID     int64
	SandboxConnectionID int64
	Prompt              *string
	MemoryPreset        *string
	Limits              []byte
	ID                  int64
	UserID              int64
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBuild,
		arg.Name,
		arg.LlmConnectionID,
		arg.SandboxConnectionID,
		arg.Prompt,
		arg.MemoryPreset,
		arg.Limits,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
