// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package db

import (
	"context"
	"time"
)

const activityByEvent = `-- name: ActivityByEvent :many
SELECT payload FROM hub.activity
 WHERE instance_id = $1 AND event_id IS NOT DISTINCT FROM $2::bigint
 ORDER BY seq, id
`

type ActivityByEventParams struct {
	InstanceID int64
	EventID    *int64
}

// Activity — реплей activity-кадров хода (тикет 012); NULL event_id = ход чата.
func (q *Queries) ActivityByEvent(ctx context.Context, arg ActivityByEventParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, activityByEvent, arg.InstanceID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activityLatest = `-- name: ActivityLatest :many
SELECT a.payload FROM hub.activity a
 WHERE a.instance_id = $1 AND a.event_id IS NOT DISTINCT FROM
       (SELECT b.event_id FROM hub.activity b WHERE b.instance_id = $1 ORDER BY b.id DESC LIMIT 1)
 ORDER BY a.seq, a.id
`

// Последний ход: группа event_id самой свежей строки.
func (q *Queries) ActivityLatest(ctx context.Context, instanceID int64) ([][]byte, error) {
	rows, err := q.db.Query(ctx, activityLatest, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSandboxInstance = `-- name: CreateSandboxInstance :one
INSERT INTO hub.sandbox_instances (external_id, sandbox_connection_id)
VALUES ($1, $2) RETURNING id
`

type CreateSandboxInstanceParams struct {
	ExternalID          string
	SandboxConnectionID int64
}

func (q *Queries) CreateSandboxInstance(ctx context.Context, arg CreateSandboxInstanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSandboxInstance, arg.ExternalID, arg.SandboxConnectionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findings = `-- name: Findings :many
SELECT id, instance_id, report_id, severity, cwe, cve, file, line_start, line_end,
       evidence, remediation, created_at
  FROM hub.findings WHERE instance_id = $1 ORDER BY id DESC
`

func (q *Queries) Findings(ctx context.Context, instanceID int64) ([]HubFinding, error) {
	rows, err := q.db.Query(ctx, findings, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubFinding
	for rows.Next() {
		var i HubFinding
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ReportID,
			&i.Severity,
			&i.CWE,
			&i.CVE,
			&i.File,
			&i.LineStart,
			&i.LineEnd,
			&i.Evidence,
			&i.Remediation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instance = `-- name: Instance :one
SELECT i.id, i.build_id, i.repository_id, i.sandbox_instance_id,
       si.external_id AS sandbox_external_id, si.status AS sandbox_status,
       i.thread_id, i.status, i.runner_id, i.updated_at
  FROM hub.agent_instances i
  JOIN hub.repositories r ON r.id = i.repository_id
  LEFT JOIN hub.sandbox_instances si ON si.id = i.sandbox_instance_id
 WHERE i.id = $1 AND r.user_id = $2
`

type InstanceParams struct {
	ID     int64
	UserID int64
}

type InstanceRow struct {
	ID                int64
	BuildID           int64
	RepositoryID      int64
	SandboxInstanceID *int64
	SandboxExternalID *string
	SandboxStatus     *string
	ThreadID          string
	Status            string
	RunnerID          *int64
	UpdatedAt         time.Time
}

func (q *Queries) Instance(ctx context.Context, arg InstanceParams) (InstanceRow, error) {
	row := q.db.QueryRow(ctx, instance, arg.ID, arg.UserID)
	var i InstanceRow
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.RepositoryID,
		&i.SandboxInstanceID,
		&i.SandboxExternalID,
		&i.SandboxStatus,
		&i.ThreadID,
		&i.Status,
		&i.RunnerID,
		&i.UpdatedAt,
	)
	return i, err
}

const instances = `-- name: Instances :many

SELECT i.id, i.build_id, i.repository_id, i.sandbox_instance_id,
       si.external_id AS sandbox_external_id, si.status AS sandbox_status,
       i.thread_id, i.status, i.runner_id, i.updated_at
  FROM hub.agent_instances i
  JOIN hub.repositories r ON r.id = i.repository_id
  LEFT JOIN hub.sandbox_instances si ON si.id = i.sandbox_instance_id
 WHERE r.user_id = $1
   AND ($2::bigint IS NULL OR i.repository_id = $2)
 ORDER BY i.id
`

type InstancesParams struct {
	UserID       int64
	RepositoryID *int64
}

type InstancesRow struct {
	ID                int64
	BuildID           int64
	RepositoryID      int64
	SandboxInstanceID *int64
	SandboxExternalID *string
	SandboxStatus     *string
	ThreadID          string
	Status            string
	RunnerID          *int64
	UpdatedAt         time.Time
}

// Экземпляры Агента, Сэндбоксы, activity, результаты
func (q *Queries) Instances(ctx context.Context, arg InstancesParams) ([]InstancesRow, error) {
	rows, err := q.db.Query(ctx, instances, arg.UserID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstancesRow
	for rows.Next() {
		var i InstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.RepositoryID,
			&i.SandboxInstanceID,
			&i.SandboxExternalID,
			&i.SandboxStatus,
			&i.ThreadID,
			&i.Status,
			&i.RunnerID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkInstanceSandbox = `-- name: LinkInstanceSandbox :execrows
UPDATE hub.agent_instances i SET sandbox_instance_id = $1::bigint, updated_at = now()
  FROM hub.repositories r
 WHERE i.id = $2 AND r.id = i.repository_id AND r.user_id = $3
`

type LinkInstanceSandboxParams struct {
	SandboxInstanceID int64
	ID                int64
	UserID            int64
}

func (q *Queries) LinkInstanceSandbox(ctx context.Context, arg LinkInstanceSandboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkInstanceSandbox, arg.SandboxInstanceID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSandboxInstanceDead = `-- name: MarkSandboxInstanceDead :exec
UPDATE hub.sandbox_instances SET status = 'dead', killed_at = now() WHERE id = $1
`

func (q *Queries) MarkSandboxInstanceDead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSandboxInstanceDead, id)
	return err
}

const reports = `-- name: Reports :many
SELECT id, instance_id, event_id, summary, created_at
  FROM hub.reports WHERE instance_id = $1 ORDER BY id DESC
`

func (q *Queries) Reports(ctx context.Context, instanceID int64) ([]HubReport, error) {
	rows, err := q.db.Query(ctx, reports, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubReport
	for rows.Next() {
		var i HubReport
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.EventID,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sandboxInstance = `-- name: SandboxInstance :one
SELECT id, external_id, sandbox_connection_id, status, created_at, killed_at
  FROM hub.sandbox_instances WHERE id = $1
`

func (q *Queries) SandboxInstance(ctx context.Context, id int64) (HubSandboxInstance, error) {
	row := q.db.QueryRow(ctx, sandboxInstance, id)
	var i HubSandboxInstance
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.SandboxConnectionID,
		&i.Status,
		&i.CreatedAt,
		&i.KilledAt,
	)
	return i, err
}

const sandboxInstances = `-- name: SandboxInstances :many
SELECT id, external_id, sandbox_connection_id, status, created_at, killed_at
  FROM hub.sandbox_instances ORDER BY id DESC
`

func (q *Queries) SandboxInstances(ctx context.Context) ([]HubSandboxInstance, error) {
	rows, err := q.db.Query(ctx, sandboxInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubSandboxInstance
	for rows.Next() {
		var i HubSandboxInstance
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.SandboxConnectionID,
			&i.Status,
			&i.CreatedAt,
			&i.KilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceDown = `-- name: SetInstanceDown :exec
UPDATE hub.agent_instances
   SET status = 'down', runner_id = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) SetInstanceDown(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setInstanceDown, id)
	return err
}

const setInstanceRunning = `-- name: SetInstanceRunning :exec
UPDATE hub.agent_instances
   SET status = 'running', runner_id = $1::bigint, updated_at = now() WHERE id = $2
`

type SetInstanceRunningParams struct {
	RunnerID int64
	ID       int64
}

func (q *Queries) SetInstanceRunning(ctx context.Context, arg SetInstanceRunningParams) error {
	_, err := q.db.Exec(ctx, setInstanceRunning, arg.RunnerID, arg.ID)
	return err
}
