// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type HubActivity struct {
	ID         int64
	InstanceID int64
	EventID    *int64
	Seq        int
	Kind       string
	Payload    []byte
	CreatedAt  time.Time
	TraceID    string
}

type HubAgentBuild struct {
	ID                  int64
	UserID              int64
	Name                string
	LlmConnectionID     int64
	SandboxConnectionID int64
	Prompt              *string
	MemoryPreset        *string
	Limits              []byte
	IsDefault           bool
	CreatedAt           time.Time
}

type HubAgentInstance struct {
	ID                int64
	BuildID           int64
	RepositoryID      int64
	SandboxInstanceID *int64
	ThreadID          string
	Status            string
	RunnerID          *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type HubBuildSubscription struct {
	ID           int64
	BuildID      int64
	RepositoryID int64
	Actions      []string
	RefMask      *string
	CreatedAt    time.Time
}

type HubEvent struct {
	ID           int64
	Provider     string
	DeliveryID   string
	RepositoryID int64
	Action       string
	CommitSHA    *string
	Ref          *string
	Payload      []byte
	ReceivedAt   time.Time
	TraceID      string
	BeforeSHA    *string
	BaseSHA      *string
	HeadSHA      *string
	PRNumber     *int
	PRTitle      *string
	PRBody       *string
	ChangedFiles json.RawMessage
}

type HubFinding struct {
	ID                 int64
	InstanceID         int64
	ReportID           *int64
	Severity           string
	CWE                *string
	CVE                *string
	File               *string
	LineStart          *int
	LineEnd            *int
	Evidence           *string
	Remediation        *string
	CreatedAt          time.Time
	Title              *string
	Description        *string
	Impact             *string
	Confidence         *string
	Category           *string
	References         json.RawMessage
	BlameAuthor        *string
	BlameEmail         *string
	BlameCommit        *string
	BlameDate          *time.Time
	BlameCommitMessage *string
	IntroducedBy       *string
	EventID            *int64
}

type HubIdentity struct {
	ID              int64
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  *time.Time
	CreatedAt       time.Time
}

type HubInstanceEvent struct {
	InstanceID  int64
	EventID     int64
	DedupKey    string
	ProcessedAt *time.Time
}

type HubLlmConnection struct {
	ID        int64
	UserID    int64
	Name      string
	APIBase   string
	APIKeyEnc []byte
	Model     string
	CreatedAt time.Time
}

type HubOutbox struct {
	ID          int64
	EventID     int64
	RoutingKey  string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type HubReport struct {
	ID         int64
	InstanceID int64
	EventID    *int64
	Summary    string
	CreatedAt  time.Time
	Structured json.RawMessage
}

type HubRepository struct {
	ID                int64
	UserID            int64
	IdentityID        *int64
	Provider          string
	ExternalID        string
	Owner             string
	Name              string
	DefaultBranch     *string
	WebhookProviderID *string
	WebhookSecretEnc  []byte
	ConnectedAt       time.Time
	Mode              string
}

type HubRunner struct {
	ID              int64
	Name            string
	Address         string
	Slots           int
	RegisteredAt    time.Time
	LastHeartbeatAt time.Time
}

type HubSandboxConnection struct {
	ID        int64
	Name      string
	Domain    string
	APIKeyEnc []byte
	Image     *string
	CreatedAt time.Time
}

type HubSandboxInstance struct {
	ID                  int64
	ExternalID          string
	SandboxConnectionID int64
	Status              string
	CreatedAt           time.Time
	KilledAt            *time.Time
}

type HubSession struct {
	Token     string
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
}

type HubUser struct {
	ID          int64
	DisplayName string
	CreatedAt   time.Time
}
