// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"
)

const insertEvent = `-- name: InsertEvent :one

INSERT INTO hub.events (provider, delivery_id, repository_id, action, commit_sha, ref, payload, trace_id,
                        before_sha, base_sha, head_sha, pr_number, pr_title, pr_body, changed_files)
VALUES ($1, $2, $3, $4,
        NULLIF($5::text, ''), NULLIF($6::text, ''), $7, $8,
        NULLIF($9::text, ''), NULLIF($10::text, ''), NULLIF($11::text, ''),
        NULLIF($12::int, 0), NULLIF($13::text, ''), NULLIF($14::text, ''), $15)
ON CONFLICT (provider, delivery_id) DO NOTHING
RETURNING id
`

type InsertEventParams struct {
	Provider     string
	DeliveryID   string
	RepositoryID int64
	Action       string
	CommitSHA    string
	Ref          string
	Payload      []byte
	TraceID      string
	BeforeSHA    string
	BaseSHA      string
	HeadSHA      string
	PRNumber     int
	PRTitle      string
	PRBody       string
	ChangedFiles json.RawMessage
}

// Ingest вебхука (одна транзакция в Store.Ingest) и transactional outbox
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Provider,
		arg.DeliveryID,
		arg.RepositoryID,
		arg.Action,
		arg.CommitSHA,
		arg.Ref,
		arg.Payload,
		arg.TraceID,
		arg.BeforeSHA,
		arg.BaseSHA,
		arg.HeadSHA,
		arg.PRNumber,
		arg.PRTitle,
		arg.PRBody,
		arg.ChangedFiles,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertInstanceEvent = `-- name: InsertInstanceEvent :exec
INSERT INTO hub.instance_events (instance_id, event_id, dedup_key)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertInstanceEventParams struct {
	InstanceID int64
	EventID    int64
	DedupKey   string
}

func (q *Queries) InsertInstanceEvent(ctx context.Context, arg InsertInstanceEventParams) error {
	_, err := q.db.Exec(ctx, insertInstanceEvent, arg.InstanceID, arg.EventID, arg.DedupKey)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO hub.outbox (event_id, routing_key, payload) VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	EventID    int64
	RoutingKey string
	Payload    []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.EventID, arg.RoutingKey, arg.Payload)
	return err
}

const markPublished = `-- name: MarkPublished :exec
UPDATE hub.outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPublished, id)
	return err
}

const unpublished = `-- name: Unpublished :many
SELECT id, routing_key, payload FROM hub.outbox
 WHERE published_at IS NULL ORDER BY id LIMIT $1::int
`

type UnpublishedRow struct {
	ID         int64
	RoutingKey string
	Payload    []byte
}

func (q *Queries) Unpublished(ctx context.Context, rowLimit int) ([]UnpublishedRow, error) {
	rows, err := q.db.Query(ctx, unpublished, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnpublishedRow
	for rows.Next() {
		var i UnpublishedRow
		if err := rows.Scan(&i.ID, &i.RoutingKey, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstance = `-- name: UpsertInstance :one
INSERT INTO hub.agent_instances (build_id, repository_id, thread_id)
VALUES ($1, $2, $3)
ON CONFLICT (build_id, repository_id) DO UPDATE SET updated_at = now()
RETURNING id, thread_id
`

type UpsertInstanceParams struct {
	BuildID      int64
	RepositoryID int64
	ThreadID     string
}

type UpsertInstanceRow struct {
	ID       int64
	ThreadID string
}

func (q *Queries) UpsertInstance(ctx context.Context, arg UpsertInstanceParams) (UpsertInstanceRow, error) {
	row := q.db.QueryRow(ctx, upsertInstance, arg.BuildID, arg.RepositoryID, arg.ThreadID)
	var i UpsertInstanceRow
	err := row.Scan(&i.ID, &i.ThreadID)
	return i, err
}
