// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"
	"time"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO hub.repositories
  (user_id, identity_id, mode, provider, external_id, owner, name, default_branch, webhook_secret_enc)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateRepositoryParams struct {
	UserID           int64
	IdentityID       *int64
	Mode             string
	Provider         string
	ExternalID       string
	Owner            string
	Name             string
	DefaultBranch    *string
	WebhookSecretEnc []byte
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.UserID,
		arg.IdentityID,
		arg.Mode,
		arg.Provider,
		arg.ExternalID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.WebhookSecretEnc,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const defaultBuild = `-- name: DefaultBuild :one
SELECT id, user_id, name FROM hub.agent_builds
 WHERE user_id = $1 AND is_default ORDER BY id LIMIT 1
`

type DefaultBuildRow struct {
	ID     int64
	UserID int64
	Name   string
}

func (q *Queries) DefaultBuild(ctx context.Context, userID int64) (DefaultBuildRow, error) {
	row := q.db.QueryRow(ctx, defaultBuild, userID)
	var i DefaultBuildRow
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM hub.repositories WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM hub.build_subscriptions bs
 USING hub.repositories r
 WHERE bs.id = $1 AND r.id = bs.repository_id AND r.user_id = $2
`

type DeleteSubscriptionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const events = `-- name: Events :many
SELECT id, provider, action, commit_sha, ref, received_at, trace_id
  FROM hub.events WHERE repository_id = $1 ORDER BY id DESC LIMIT $2::int
`

type EventsParams struct {
	RepositoryID int64
	RowLimit     int
}

type EventsRow struct {
	ID         int64
	Provider   string
	Action     string
	CommitSHA  *string
	Ref        *string
	ReceivedAt time.Time
	TraceID    string
}

func (q *Queries) Events(ctx context.Context, arg EventsParams) ([]EventsRow, error) {
	rows, err := q.db.Query(ctx, events, arg.RepositoryID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsRow
	for rows.Next() {
		var i EventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Action,
			&i.CommitSHA,
			&i.Ref,
			&i.ReceivedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRepository = `-- name: FindRepository :one

SELECT user_id, owner, name, webhook_secret_enc
  FROM hub.repositories WHERE id = $1 AND provider = $2
`

type FindRepositoryParams struct {
	ID       int64
	Provider string
}

type FindRepositoryRow struct {
	UserID           int64
	Owner            string
	Name             string
	WebhookSecretEnc []byte
}

// Репозитории, События, подписки Сборок (тикет 011)
func (q *Queries) FindRepository(ctx context.Context, arg FindRepositoryParams) (FindRepositoryRow, error) {
	row := q.db.QueryRow(ctx, findRepository, arg.ID, arg.Provider)
	var i FindRepositoryRow
	err := row.Scan(
		&i.UserID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecretEnc,
	)
	return i, err
}

const repositories = `-- name: Repositories :many
SELECT r.id, r.user_id, r.identity_id, r.mode, r.provider, r.external_id, r.owner, r.name,
       r.default_branch, r.webhook_provider_id, r.webhook_secret_enc, bs.build_id, r.connected_at
  FROM hub.repositories r
  LEFT JOIN hub.build_subscriptions bs
         ON bs.id = (SELECT min(id) FROM hub.build_subscriptions WHERE repository_id = r.id)
 WHERE r.user_id = $1 ORDER BY r.id
`

type RepositoriesRow struct {
	ID                int64
	UserID            int64
	IdentityID        *int64
	Mode              string
	Provider          string
	ExternalID        string
	Owner             string
	Name              string
	DefaultBranch     *string
	WebhookProviderID *string
	WebhookSecretEnc  []byte
	BuildID           *int64
	ConnectedAt       time.Time
}

// build_id — derived: Сборка первой подписки (deprecated wire-поле, тикет 011);
// LEFT JOIN на таблицу (не derived) — так sqlc выводит nullable *int64.
func (q *Queries) Repositories(ctx context.Context, userID int64) ([]RepositoriesRow, error) {
	rows, err := q.db.Query(ctx, repositories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoriesRow
	for rows.Next() {
		var i RepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IdentityID,
			&i.Mode,
			&i.Provider,
			&i.ExternalID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.WebhookProviderID,
			&i.WebhookSecretEnc,
			&i.BuildID,
			&i.ConnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repository = `-- name: Repository :one
SELECT r.id, r.user_id, r.identity_id, r.mode, r.provider, r.external_id, r.owner, r.name,
       r.default_branch, r.webhook_provider_id, r.webhook_secret_enc, bs.build_id, r.connected_at
  FROM hub.repositories r
  LEFT JOIN hub.build_subscriptions bs
         ON bs.id = (SELECT min(id) FROM hub.build_subscriptions WHERE repository_id = r.id)
 WHERE r.id = $1 AND r.user_id = $2
`

type RepositoryParams struct {
	ID     int64
	UserID int64
}

type RepositoryRow struct {
	ID                int64
	UserID            int64
	IdentityID        *int64
	Mode              string
	Provider          string
	ExternalID        string
	Owner             string
	Name              string
	DefaultBranch     *string
	WebhookProviderID *string
	WebhookSecretEnc  []byte
	BuildID           *int64
	ConnectedAt       time.Time
}

func (q *Queries) Repository(ctx context.Context, arg RepositoryParams) (RepositoryRow, error) {
	row := q.db.QueryRow(ctx, repository, arg.ID, arg.UserID)
	var i RepositoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityID,
		&i.Mode,
		&i.Provider,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.WebhookProviderID,
		&i.WebhookSecretEnc,
		&i.BuildID,
		&i.ConnectedAt,
	)
	return i, err
}

const setWebhook = `-- name: SetWebhook :exec
UPDATE hub.repositories SET webhook_provider_id = $1 WHERE id = $2
`

type SetWebhookParams struct {
	WebhookProviderID *string
	ID                int64
}

func (q *Queries) SetWebhook(ctx context.Context, arg SetWebhookParams) error {
	_, err := q.db.Exec(ctx, setWebhook, arg.WebhookProviderID, arg.ID)
	return err
}

const subscriptionsByRepo = `-- name: SubscriptionsByRepo :many
SELECT id, build_id, repository_id, actions, ref_mask, created_at
  FROM hub.build_subscriptions WHERE repository_id = $1 ORDER BY id
`

func (q *Queries) SubscriptionsByRepo(ctx context.Context, repositoryID int64) ([]HubBuildSubscription, error) {
	rows, err := q.db.Query(ctx, subscriptionsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubBuildSubscription
	for rows.Next() {
		var i HubBuildSubscription
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.RepositoryID,
			&i.Actions,
			&i.RefMask,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO hub.build_subscriptions (build_id, repository_id, actions, ref_mask)
VALUES ($1, $2, COALESCE($3::text[], '{}'::text[]), $4)
ON CONFLICT (build_id, repository_id) DO UPDATE
  SET actions = COALESCE($3::text[], '{}'::text[]), ref_mask = $4
RETURNING id
`

type UpsertSubscriptionParams struct {
	BuildID      int64
	RepositoryID int64
	Actions      []string
	RefMask      *string
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.BuildID,
		arg.RepositoryID,
		arg.Actions,
		arg.RefMask,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
