// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package db

import (
	"context"
	"time"
)

const aliveRunner = `-- name: AliveRunner :one
SELECT id, name, address, slots, last_heartbeat_at
  FROM hub.runners
 WHERE last_heartbeat_at > now() - $1::interval
 ORDER BY last_heartbeat_at DESC LIMIT 1
`

type AliveRunnerRow struct {
	ID              int64
	Name            string
	Address         string
	Slots           int
	LastHeartbeatAt time.Time
}

func (q *Queries) AliveRunner(ctx context.Context, aliveWithin time.Duration) (AliveRunnerRow, error) {
	row := q.db.QueryRow(ctx, aliveRunner, aliveWithin)
	var i AliveRunnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Slots,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const heartbeatRunner = `-- name: HeartbeatRunner :execrows
UPDATE hub.runners SET last_heartbeat_at = now() WHERE id = $1
`

func (q *Queries) HeartbeatRunner(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueInstance = `-- name: RequeueInstance :many
WITH targets AS (SELECT $1::bigint AS id)
INSERT INTO hub.outbox (event_id, routing_key, payload)
SELECT ie.event_id, o.routing_key, o.payload
  FROM hub.instance_events ie
  JOIN targets t ON t.id = ie.instance_id
  JOIN LATERAL (SELECT routing_key, payload FROM hub.outbox o2
                 WHERE o2.event_id = ie.event_id
                   AND (o2.payload->>'instanceId')::bigint = ie.instance_id
                 ORDER BY o2.id LIMIT 1) o ON true
 WHERE ie.processed_at IS NULL
 RETURNING event_id
`

// RequeueInstance — «Продолжить»: незавершённые События одного Экземпляра —
// снова в outbox; возвращает пере-опубликованные eventId (пусто = нечего продолжать).
func (q *Queries) RequeueInstance(ctx context.Context, instanceID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, requeueInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var event_id int64
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStale = `-- name: RequeueStale :one

WITH targets AS (
    UPDATE hub.agent_instances SET status = 'down', runner_id = NULL, updated_at = now()
     WHERE status = 'running'
       AND runner_id IN (SELECT id FROM hub.runners WHERE last_heartbeat_at < now() - $1::interval)
     RETURNING id
), requeued AS (
    INSERT INTO hub.outbox (event_id, routing_key, payload)
    SELECT ie.event_id, o.routing_key, o.payload
      FROM hub.instance_events ie
      JOIN targets t ON t.id = ie.instance_id
      JOIN LATERAL (SELECT routing_key, payload FROM hub.outbox o2
                     WHERE o2.event_id = ie.event_id
                       AND (o2.payload->>'instanceId')::bigint = ie.instance_id
                     ORDER BY o2.id LIMIT 1) o ON true
     WHERE ie.processed_at IS NULL
     RETURNING event_id
)
SELECT (SELECT count(*) FROM targets)::int AS downed, (SELECT count(*) FROM requeued)::int AS requeued
`

type RequeueStaleRow struct {
	Downed   int
	Requeued int
}

// Ре-публикация (heartbeat + resume): незавершённые События (instance_events без
// processed_at) Экземпляров из CTE targets(id) — новыми строками outbox;
// routing_key/payload копируются из исходной публикации ЭТОГО Экземпляра
// (по instanceId в payload — при веере одного События на несколько Экземпляров
// строки outbox различаются). SQL продублирован в двух запросах ниже: sqlc не
// умеет композицию фрагментов.
// RequeueStale — один стейтмент: running-Экземпляры протухших Раннеров → down,
// их необработанные События — снова в outbox.
func (q *Queries) RequeueStale(ctx context.Context, timeout time.Duration) (RequeueStaleRow, error) {
	row := q.db.QueryRow(ctx, requeueStale, timeout)
	var i RequeueStaleRow
	err := row.Scan(&i.Downed, &i.Requeued)
	return i, err
}

const runner = `-- name: Runner :one
SELECT id, name, address, slots, last_heartbeat_at FROM hub.runners WHERE id = $1
`

type RunnerRow struct {
	ID              int64
	Name            string
	Address         string
	Slots           int
	LastHeartbeatAt time.Time
}

func (q *Queries) Runner(ctx context.Context, id int64) (RunnerRow, error) {
	row := q.db.QueryRow(ctx, runner, id)
	var i RunnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Slots,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const runners = `-- name: Runners :many
SELECT id, name, address, slots, last_heartbeat_at FROM hub.runners ORDER BY id
`

type RunnersRow struct {
	ID              int64
	Name            string
	Address         string
	Slots           int
	LastHeartbeatAt time.Time
}

func (q *Queries) Runners(ctx context.Context) ([]RunnersRow, error) {
	rows, err := q.db.Query(ctx, runners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunnersRow
	for rows.Next() {
		var i RunnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Slots,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunner = `-- name: UpsertRunner :one

INSERT INTO hub.runners (name, address, slots)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
  SET address = $2, slots = $3, last_heartbeat_at = now()
RETURNING id
`

type UpsertRunnerParams struct {
	Name    string
	Address string
	Slots   int
}

// Раннеры и надзор за heartbeat
func (q *Queries) UpsertRunner(ctx context.Context, arg UpsertRunnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRunner, arg.Name, arg.Address, arg.Slots)
	var id int64
	err := row.Scan(&id)
	return id, err
}
